language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: reuiVcM+K0Y9ZxNmLjNSBVWoT7TUu4iYxLc08YThjqdnZxmXS2gg0TX0rtAkmOdgm3/k/Tj4JTvuttxtXbZf4TK1GYggkba2tmDa18z6eNuwUAnal0dswNUSq6gFbZAzrwUKglDBM/TxTvHKVGaBNe3brKGgpQC3TK92sYN1jfJ6tSeQbvTj+p0zR6XWju6lPGhH4VFm79CfePsqWQ2I8sI8P2+LAL+WZB/UATFs3eViWkFBPX6w+PKq5dTp1RN8d/lkwMJjal38u/XkxfxH3JhmaKbYbm6vMO1iaWCaXhdBjZLMvw+O074Ajdx3hxgDI7vN0z0yRsVvfHXGfW9B9vivXhIjbOaQbM0E6HBR4HrY5pdINTO9w9uMW2SUEyP+lqiBdO3boCXFgBRaVtMenF3DL3foKJdH7Np8lEcnEMbcRNA6akv8rh/yhXPGADESf91c2u6aeiBZvSEO5Tl89A02mx0IHxVGrqYLFbQRSyDteibnm6dvqzZJ7AjbUUbhZjqOpwPzGKlGX2tmlywglbXQFdRKKoE6Ka2PFKNLjaanvZ8LWLQo3qJgya3MWN0CkdSiGSW6qZxs+B1jHUlTBuo/pwfKOHpv4y4SZohsm17EzyaNDXk+HKujEF/N3WyggiVJAAyefhsHiUOMStO00qevWbhPlnG8kpuRyhxmtBE=
  app: expense-manager-capstone
  on:
    repo: lavanya-sethuraman/expense-manager-api
