language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: enVAXnfeLiA9VovUU/0/ylr+7SHeHXgfBK5nkYtjmlk4IVZZwcgObhRKh5WpK9xH1865ZZe1LSxCd7qwDCkvJhof1RZ6PPOMRa5yST5Q/ME5q0+gV5GkEtrIDAHtntT/xh0u65mtFPFT7sY4xvW/hpcdmnfYAoyR7OUYj+o7ZApDmStWyEW1/2wnRtqeAwXbUqTWaRQ4Hxr6rLajGDkmSuWDTt5T6/cFSTeg2nEBjDOVfsXu1vMWaIwFzrOj7Vzh7oRVy9vl6jQwnEX5vI/4PqMKsC9ezKaa/ab4/10XOe4e+lNnbYTe2pezilvtXpOoU8LwMfLchVdY4/1R2TyRHtD1HdRQnBAAnC1ppyYqOisYjO4Fp1doIUxUPwAYlKMCq+jzT7IR3DHgVUBZGn3KWNGgUaOWT9CqLLDqr+SHzYkbFJr9NFpTnb+o0ShbgVb0Zx8QnTJPhM0pvgECqLrrAnrT7jNuHRdaPTPk5Ld+5su5EaWfhUSYWEZBJlW8eU6SZUqYUdeEJrbcho+mqv/X38MW6+2B+PCXGuVzI9teeN4ga+j/kgY40zak4kL4ZxpdOZPSuenQAIB4IBRsl4kbLSQdek4r/annh7z7myCVCounTBHc3CowIjt12DHSvWQOhZS5azEyHsPAKIkxxHthvv5j+WaTxLR+59K/1gG9B18=
  app: expense-manager-capstone-api
  on:
    repo: lavanya-sethuraman/expense-manager-api
