language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: kpwWjHiqmI5iWI/gV9jNIqMU3wAFWzSV0xDs634SxZZdhadmvZiQEsngBF6Nn3xtHl9+KuUxp8BbsZh3bI1HghNwl6ZNiadfHXF3g/os9TlKIAiDV7Il8rsLnKmTLyNtYATBYTyRil8wBGFRDQiEQMEqmXpkWrzkmXBHbQc2YyIet8rBZn7OTMxvsPXuNznjWev6KSDteQd4N05hyYf/fN5Jp1Po+HQUpBQVj0RXsisABSfpt0bOMNyr2mzfvwupdjSKe+s42l8TGBOogMKUiFWd2ESWX8ifK2hzviGyG3W21GqwadOeRuRVXtKuYjnRGLMBzLxLravkE+/mH0cPak+uuoojMUGfXZjQ/SN8TN3Ln+cl2rFKAX/Ho8lgZDGHAhyerDgKFZrxxCC8lyKwzAlIKB8wwg8hgU+tYBXlAkEAyGr19N/EvJ4iMPf6/r+2SsTsVlSLY2zfDcgo5uRZJ8zhaQvNkxHmJXVCMDs2BrTjRi74HBenvfcjtiziOag9Jpz8FaDE2NWfO76azOQOR2t0/u70gD+H7ivlfEVgBsWF474EvUcOZDTduUbSbbeO2QbeYhs/141nOxTYZQJwEkwrklvwvTtMgPVnbiV567NVhUJfjZ0WSukoEHvxwEWElQKjWXjNpHcafv6M7kXqBn/tfodTutewQqwpqAirr3g=
  app: expense-manager-capstone
  on:
    repo: lavanya-sethuraman/expense-manager-api
